
WITH DATES AS (
	SELECT
		ORDER_DATE_ADDED,
		COALESCE(ORDER_DATE_DISPENSED, NOW()) AS ORDER_DATE_LAST,
		GENERATE_SERIES(
			DATE(ORDER_DATE_ADDED),
			DATE(COALESCE(ORDER_DATE_DISPENSED, NOW())),
			'1 DAY'::INTERVAL)::timestamp AS DATE_BETWEEN
	FROM "datawarehouse".goodpill."orders"
),
FILTER_CASES AS (
	SELECT
		DATE_BETWEEN
	from DATES
	WHERE
		ORDER_DATE_ADDED <= DATE_BETWEEN + INTERVAL '1' DAY
		AND ORDER_DATE_LAST > DATE_BETWEEN + INTERVAL '1' DAY
)
SELECT
	DATE_BETWEEN as day,
	COUNT(*) as active_orders_count
from FILTER_CASES
GROUP by DATE_BETWEEN