
with patients as (
    select
    patient_id_cp,
    patient_id_wc,
    patient_date_registered,
    patient_date_reviewed,
    patient_date_added,
    patient_date_changed,
    patient_date_updated,
    first_name as patient_first_name,
    last_name as patient_last_name,
    birth_date as patient_birth_date,
    birth_date as patient_language,
    phone1 as patient_phone1,
    phone2 as patient_phone2,
    concat(patient_address1, ', ', patient_address2) as patient_address,
    patient_city as patient_city,
    patient_state as patient_state,
    patient_zip as patient_zip,
    payment_card_type as patient_payment_card_type,
    payment_card_last4 as patient_payment_card_last4,
    payment_card_date_expired as patient_payment_card_date_expired,
    payment_card_autopay as patient_payment_card_autopay,
    payment_method_default as patient_payment_method_default,
    patient_date_first_rx_received,
    patient_date_first_dispensed,
    patient_date_first_expected_by,
    refills_used as patient_refills_used,
    email as patient_email,
    patient_autofill,
    initial_invoice_number as patient_initial_invoice_number,
    patient_note,
    allergies_none as patient_allergies_none,
    allergies_cephalosporins as patient_allergies_cephalosporins,
    allergies_sulfa as patient_allergies_sulfa,
    allergies_aspirin as patient_allergies_aspirin,
    allergies_penicillin as patient_allergies_penicillin,
    allergies_erythromycin as patient_allergies_erythromycin,
    allergies_codeine as patient_allergies_codeine,
    allergies_nsaids as patient_allergies_nsaids,
    allergies_salicylates as patient_allergies_salicylates,
    allergies_azithromycin as patient_allergies_azithromycin,
    allergies_amoxicillin as patient_allergies_amoxicillin,
    allergies_tetracycline as patient_allergies_tetracycline,
    allergies_other as patient_allergies_other,
    medications_other as patient_medications_other,
    pharmacy_npi as pharmacy_npi,
    pharmacy_name as pharmacy_name,
    pharmacy_phone as pharmacy_phone,
    pharmacy_fax as pharmacy_fax,
    pharmacy_address as pharmacy_address,
    patient_inactive,
    payment_coupon as patient_payment_coupon,
    tracking_coupon as patient_tracking_coupon,
    patient_deleted as patient_patient_deleted,
    third_party_id as patient_third_party_id,
    terms_viewed_at as patient_terms_viewed_at,
    terms_accepted as patient_terms_accepted
    from "datawarehouse".goodpill."patients"
),
patient_comms as (
    select
    patient_comms_comm_id,
    event as patient_comms_event,
    data_type as patient_comms_data_type,
    date_sent as patient_comms_date_sent,
    created_at as patient_comms_created_at,
    updated_at as patient_comms_updated_at,
    date_to_send as patient_comms_date_to_send,
    patient_id_cp as patient_comms_patient_id_cp,
    invoice_number as patient_comms_invoice_number,
    group_id as patient_comms_group_id ,
    rx_number as patient_comms_rx_number ,
    date_deleted as patient_comms_date_deleted,
    meta_json as patient_comms_meta_json,
    email_subject as patient_comms_email_subject,
    sms as patient_comms_sms,
    email_body as patient_comms_email_body
    from "datawarehouse".goodpill."patient_comms"
)
select * from patients
left join patient_comms on patient_comms.patient_comms_patient_id_cp = patients.patient_id_cp