select
    cast(jsonb_extract_path_text(_airbyte_data, 'drug_generic') as varchar) as drug_generic,
    cast(jsonb_extract_path_text(_airbyte_data, 'drug_brand') as varchar) as drug_brand,
    cast(jsonb_extract_path_text(_airbyte_data, 'drug_gsns') as varchar) as drug_gsns,
    cast(jsonb_extract_path_text(_airbyte_data, 'message_display') as varchar) as message_display,
    cast(jsonb_extract_path_text(_airbyte_data, 'price_per_month') as decimal(5,2)) as price_per_month,
    cast(jsonb_extract_path_text(_airbyte_data, 'drug_ordered') as int) as drug_ordered,
    cast(jsonb_extract_path_text(_airbyte_data, 'qty_repack') as int) as qty_repack,
    cast(jsonb_extract_path_text(_airbyte_data, 'months_inventory') as varchar) as months_inventory,
    cast(jsonb_extract_path_text(_airbyte_data, 'avg_inventory') as decimal(10,1)) as avg_inventory,
    cast(jsonb_extract_path_text(_airbyte_data, 'last_inventory') as decimal(10,1)) as last_inventory,
    cast(jsonb_extract_path_text(_airbyte_data, 'months_entered') as varchar) as months_entered,
    cast(jsonb_extract_path_text(_airbyte_data, 'stddev_entered') as decimal(10,1)) as stddev_entered,
    cast(jsonb_extract_path_text(_airbyte_data, 'total_entered') as decimal(10,1)) as total_entered,
    cast(jsonb_extract_path_text(_airbyte_data, 'months_dispensed') as varchar) as months_dispensed,
    cast(jsonb_extract_path_text(_airbyte_data, 'stddev_dispensed_actual') as decimal(10,1)) as stddev_dispensed_actual,
    cast(jsonb_extract_path_text(_airbyte_data, 'total_dispensed_actual') as decimal(10,1)) as total_dispensed_actual,
    cast(jsonb_extract_path_text(_airbyte_data, 'total_dispensed_default') as decimal(10,1)) as total_dispensed_default,
    cast(jsonb_extract_path_text(_airbyte_data, 'stddev_dispensed_default') as decimal(10,1)) as stddev_dispensed_default,
    cast(jsonb_extract_path_text(_airbyte_data, 'month_interval') as int) as month_interval,
    cast(jsonb_extract_path_text(_airbyte_data, 'default_rxs_min') as decimal(5,2)) as default_rxs_min,
    cast(jsonb_extract_path_text(_airbyte_data, 'last_inv_low_threshold') as decimal(10,1)) as last_inv_low_threshold,
    cast(jsonb_extract_path_text(_airbyte_data, 'last_inv_high_threshold') as decimal(10,1)) as last_inv_high_threshold,
    cast(jsonb_extract_path_text(_airbyte_data, 'last_inv_onetime_threshold') as decimal(10,1)) as last_inv_onetime_threshold,
    cast(jsonb_extract_path_text(_airbyte_data, 'zlow_threshold') as decimal(5,3)) as zlow_threshold,
    cast(jsonb_extract_path_text(_airbyte_data, 'zhigh_threshold') as decimal(5,3)) as zhigh_threshold,
    cast(jsonb_extract_path_text(_airbyte_data, 'zscore') as decimal(6,3)) as zscore,
    cast(jsonb_extract_path_text(_airbyte_data, 'stock_level') as varchar) as stock_level
from
    "datawarehouse"."raw"._airbyte_raw_goodpill_gp_stock_live