with rxs_grouped as (
    select
        _airbyte_emitted_at,
        _airbyte_ab_id,
        cast(jsonb_extract_path_text(_airbyte_data, 'patient_id_cp') as int) as patient_id_cp,
        cast(jsonb_extract_path_text(_airbyte_data, 'drug_generic') as varchar(255)) as drug_generic,
        cast(jsonb_extract_path_text(_airbyte_data, 'drug_brand') as varchar(255)) as drug_brand,
        cast(jsonb_extract_path_text(_airbyte_data, 'group_id') as int) as group_id,
        cast(jsonb_extract_path_text(_airbyte_data, 'sig_qty_per_day') as decimal(6, 3)) as sig_qty_per_day,
        cast(jsonb_extract_path_text(_airbyte_data, 'rx_message_keys') as varchar(255)) as rx_message_keys,
        cast(jsonb_extract_path_text(_airbyte_data, 'rx_message_date') as timestamp) as rx_message_date,
        cast(jsonb_extract_path_text(_airbyte_data, 'max_gsn') as int) as max_gsn,
        cast(jsonb_extract_path_text(_airbyte_data, 'drug_gsns') as varchar(255)) as drug_gsns,
        cast(jsonb_extract_path_text(_airbyte_data, 'refills_total') as decimal(5, 2)) as refills_total,
        cast(jsonb_extract_path_text(_airbyte_data, 'qty_total') as decimal(11, 3)) as qty_total,
        cast(jsonb_extract_path_text(_airbyte_data, 'rx_autofill') as int) as rx_autofill,
        cast(jsonb_extract_path_text(_airbyte_data, 'refill_date_first') as timestamp) as refill_date_first,
        cast(jsonb_extract_path_text(_airbyte_data, 'refill_date_last') as timestamp) as refill_date_last,
        cast(jsonb_extract_path_text(_airbyte_data, 'refill_date_next') as timestamp) as refill_date_next,
        cast(jsonb_extract_path_text(_airbyte_data, 'refill_date_manual') as timestamp) as refill_date_manual,
        cast(jsonb_extract_path_text(_airbyte_data, 'refill_date_default') as timestamp) as refill_date_default,
        cast(jsonb_extract_path_text(_airbyte_data, 'best_rx_number') as int) as best_rx_number,
        cast(jsonb_extract_path_text(_airbyte_data, 'rx_numbers') as varchar(255)) as rx_numbers,
        cast(jsonb_extract_path_text(_airbyte_data, 'rx_sources') as varchar(80)) as rx_sources,
        cast(jsonb_extract_path_text(_airbyte_data, 'rx_date_changed') as timestamp) as rx_date_changed,
        cast(jsonb_extract_path_text(_airbyte_data, 'rx_date_expired') as timestamp) as rx_date_expired,
        cast(jsonb_extract_path_text(_airbyte_data, 'rx_date_transferred') as timestamp) as rx_date_transferred,
        cast(jsonb_extract_path_text(_airbyte_data, 'created_at') as timestamp) as created_at,
        cast(jsonb_extract_path_text(_airbyte_data, 'rx_added_first_at') as timestamp) as rx_added_first_at,
        cast(jsonb_extract_path_text(_airbyte_data, 'rx_added_last_at') as timestamp) as rx_added_last_at,
        cast(jsonb_extract_path_text(_airbyte_data, 'updated_at') as timestamp) as updated_at,
        cast(jsonb_extract_path_text(_airbyte_data, 'rx_inactivated_last_at') as timestamp) as rx_inactivated_last_at,
        cast(jsonb_extract_path_text(_airbyte_data, 'rx_activated_last_at') as timestamp) as rx_activated_last_at,
        cast(jsonb_extract_path_text(_airbyte_data, 'group_status') as varchar(255)) as group_status
    from
        "datawarehouse"."raw"._airbyte_raw_goodpill_gp_rxs_grouped
)

select
    _airbyte_emitted_at,
    _airbyte_ab_id,
    patient_id_cp,
    nullif(drug_generic, '') as drug_generic,
    nullif(drug_brand, '') as drug_brand,
    group_id,
    sig_qty_per_day,
    nullif(rx_message_keys, '') as rx_message_keys,
    rx_message_date,
    max_gsn,
    nullif(drug_gsns, '') as drug_gsns,
    refills_total,
    qty_total,
    rx_autofill,
    refill_date_first,
    refill_date_last,
    refill_date_next,
    refill_date_manual,
    refill_date_default,
    best_rx_number,
    nullif(rx_numbers, '') as rx_numbers,
    nullif(rx_sources, '') as rx_sources,
    rx_date_changed,
    rx_date_expired,
    rx_date_transferred,
    rx_added_first_at,
    rx_added_last_at,
    created_at,
    updated_at,
    rx_inactivated_last_at,
    rx_activated_last_at,
    group_status
from rxs_grouped
