

-- depends on __dbt__cte__an_fills_logs
-- depends on __dbt__cte__an_patients
-- depends on __dbt__cte__an_providers
-- depends on __dbt__cte__an_drugs
-- depends on __dbt__cte__an_clinics
-- depends on __dbt__cte__gp_rxs_single
-- depends on __dbt__cte__gp_rxs_single
-- depends on __dbt__cte__gp_rxs_single
-- depends on __dbt__cte__gp_rxs_grouped
-- depends on __dbt__cte__gp_patients

with  __dbt__cte__an_fills_logs as (
select
	_airbyte_ab_id,
	_airbyte_emitted_at,
	cast(jsonb_extract_path_text(_airbyte_data, 'patient_id') as int) as patient_id,
	cast(jsonb_extract_path_text(_airbyte_data, 'event_date_id') as int) as event_date_id,
	cast(jsonb_extract_path_text(_airbyte_data, 'event_time_id') as int) as event_time_id,
	cast(jsonb_extract_path_text(_airbyte_data, 'event_type') as varchar(15)) as event_type,
	cast(jsonb_extract_path_text(_airbyte_data, 'goodpill_event_date') as timestamp) as goodpill_event_date,
	cast(jsonb_extract_path_text(_airbyte_data, 'rx_number') as int) as rx_number,
	cast(jsonb_extract_path_text(_airbyte_data, 'provider_id') as int) as provider_id,
	cast(jsonb_extract_path_text(_airbyte_data, 'drug_id') as int) as drug_id,
	cast(jsonb_extract_path_text(_airbyte_data, 'clinic_id') as int) as clinic_id,
	cast(jsonb_extract_path_text(_airbyte_data, 'location_id') as int) as location_id,
	cast(jsonb_extract_path_text(_airbyte_data, 'invoice_number') as int) as invoice_number,
	cast(jsonb_extract_path_text(_airbyte_data, 'is_refill') as int) as is_refill,
	cast(jsonb_extract_path_text(_airbyte_data, 'rx_autofill') as int) as rx_autofill,
	cast(jsonb_extract_path_text(_airbyte_data, 'sig_qty_per_day') as decimal(6,3)) as sig_qty_per_day,
	cast(jsonb_extract_path_text(_airbyte_data, 'rx_message_key') as varchar(80)) as rx_message_key,
	cast(jsonb_extract_path_text(_airbyte_data, 'max_gsn') as int) as max_gsn,
	cast(jsonb_extract_path_text(_airbyte_data, 'drug_gsns') as varchar(255)) as drug_gsns,
	cast(jsonb_extract_path_text(_airbyte_data, 'refills_total') as decimal(5,2)) as refills_total,
	cast(jsonb_extract_path_text(_airbyte_data, 'refills_original') as decimal(5,2)) as refills_original,
	cast(jsonb_extract_path_text(_airbyte_data, 'refills_left') as decimal(5,2)) as refills_left,
	cast(jsonb_extract_path_text(_airbyte_data, 'refill_date_first') as date) as refill_date_first,
	cast(jsonb_extract_path_text(_airbyte_data, 'refill_date_last') as date) as refill_date_last,
	cast(jsonb_extract_path_text(_airbyte_data, 'rx_date_changed') as timestamp) as rx_date_changed,
	cast(jsonb_extract_path_text(_airbyte_data, 'rx_date_expired') as date) as rx_date_expired,
	cast(jsonb_extract_path_text(_airbyte_data, 'qty_left') as decimal(10,3)) as qty_left,
	cast(jsonb_extract_path_text(_airbyte_data, 'qty_original') as decimal(10,3)) as qty_original,
	cast(jsonb_extract_path_text(_airbyte_data, 'stock_level_initial') as varchar(80)) as stock_level_initial,
	cast(jsonb_extract_path_text(_airbyte_data, 'sig_actual') as varchar(255)) as sig_actual,
	cast(jsonb_extract_path_text(_airbyte_data, 'sig_initial') as varchar(255)) as sig_initial,
	cast(jsonb_extract_path_text(_airbyte_data, 'sig_clean') as varchar(255)) as sig_clean,
	cast(jsonb_extract_path_text(_airbyte_data, 'sig_qty') as decimal(10,3)) as sig_qty,
	cast(jsonb_extract_path_text(_airbyte_data, 'sig_days') as int) as sig_days,
	cast(jsonb_extract_path_text(_airbyte_data, 'sig_qty_per_day_actual') as decimal(10,3)) as sig_qty_per_day_actual,
	cast(jsonb_extract_path_text(_airbyte_data, 'sig_durations') as varchar(255)) as sig_durations,
	cast(jsonb_extract_path_text(_airbyte_data, 'sig_qtys_per_time') as varchar(255)) as sig_qtys_per_time,
	cast(jsonb_extract_path_text(_airbyte_data, 'sig_frequencies') as varchar(255)) as sig_frequencies,
	cast(jsonb_extract_path_text(_airbyte_data, 'sig_frequency_numerators') as varchar(255)) as sig_frequency_numerators,
	cast(jsonb_extract_path_text(_airbyte_data, 'sig_frequency_denominators') as varchar(255)) as sig_frequency_denominators,
	cast(jsonb_extract_path_text(_airbyte_data, 'sig_v2_qty') as decimal(10,3)) as sig_v2_qty,
	cast(jsonb_extract_path_text(_airbyte_data, 'sig_v2_days') as int) as sig_v2_days,
	cast(jsonb_extract_path_text(_airbyte_data, 'sig_v2_qty_per_day') as decimal(10,3)) as sig_v2_qty_per_day,
	cast(jsonb_extract_path_text(_airbyte_data, 'sig_v2_unit') as varchar(255)) as sig_v2_unit,
	cast(jsonb_extract_path_text(_airbyte_data, 'sig_v2_conf_score') as decimal(10,3)) as sig_v2_conf_score,
	cast(jsonb_extract_path_text(_airbyte_data, 'sig_v2_dosages') as varchar(255)) as sig_v2_dosages,
	cast(jsonb_extract_path_text(_airbyte_data, 'sig_v2_scores') as varchar(255)) as sig_v2_scores,
	cast(jsonb_extract_path_text(_airbyte_data, 'sig_v2_frequencies') as varchar(255)) as sig_v2_frequencies,
	cast(jsonb_extract_path_text(_airbyte_data, 'sig_v2_durations') as varchar(255)) as sig_v2_durations,
	cast(jsonb_extract_path_text(_airbyte_data, 'refill_date_next') as date) as refill_date_next,
	cast(jsonb_extract_path_text(_airbyte_data, 'refill_date_manual') as date) as refill_date_manual,
	cast(jsonb_extract_path_text(_airbyte_data, 'refill_date_default') as date) as refill_date_default,
	cast(jsonb_extract_path_text(_airbyte_data, 'qty_total') as decimal(11,3)) as qty_total,
	cast(jsonb_extract_path_text(_airbyte_data, 'rx_source') as varchar(80)) as rx_source,
	cast(jsonb_extract_path_text(_airbyte_data, 'rx_transfer') as varchar(80)) as rx_transfer,
	cast(jsonb_extract_path_text(_airbyte_data, 'rx_message_keys_initial') as varchar(255)) as rx_message_keys_initial,
	cast(jsonb_extract_path_text(_airbyte_data, 'patient_autofill_initial') as int) as patient_autofill_initial,
	cast(jsonb_extract_path_text(_airbyte_data, 'rx_autofill_initial') as int) as rx_autofill_initial,
	cast(jsonb_extract_path_text(_airbyte_data, 'rx_numbers_initial') as varchar(255)) as rx_numbers_initial,
	cast(jsonb_extract_path_text(_airbyte_data, 'zscore_initial') as decimal(6,3)) as zscore_initial,
	cast(jsonb_extract_path_text(_airbyte_data, 'refills_dispensed_actual') as decimal(5,2)) as refills_dispensed_actual,
	cast(jsonb_extract_path_text(_airbyte_data, 'days_dispensed_actual') as int) as days_dispensed_actual,
	cast(jsonb_extract_path_text(_airbyte_data, 'days_dispensed_actual_rx30') as int) as days_dispensed_actual_rx30,
	cast(jsonb_extract_path_text(_airbyte_data, 'qty_dispensed_actual') as decimal(10,3)) as qty_dispensed_actual,
	cast(jsonb_extract_path_text(_airbyte_data, 'qty_dispensed_actual_rx30') as decimal(10,3)) as qty_dispensed_actual_rx30,
	cast(jsonb_extract_path_text(_airbyte_data, 'price_dispensed_actual') as decimal(5,2)) as price_dispensed_actual,
	cast(jsonb_extract_path_text(_airbyte_data, 'count_items') as int) as count_items,
	cast(jsonb_extract_path_text(_airbyte_data, 'count_filled') as int) as count_filled,
	cast(jsonb_extract_path_text(_airbyte_data, 'count_nofill') as int) as count_nofill,
	cast(jsonb_extract_path_text(_airbyte_data, 'total_value_coalesced') as decimal(11,3)) as total_value_coalesced,
	cast(jsonb_extract_path_text(_airbyte_data, 'unit_value_coalesced') as decimal(11,3)) as unit_value_coalesced,
	cast(jsonb_extract_path_text(_airbyte_data, 'drug_values') as text) as drug_values,
	cast(jsonb_extract_path_text(_airbyte_data, 'extra_data') as text) as extra_data,
	cast(jsonb_extract_path_text(_airbyte_data, 'date_processed') as timestamp) as date_processed
from "datawarehouse".raw._airbyte_raw_analytics_fills_logs
),  __dbt__cte__an_patients as (
select
	_airbyte_ab_id,
	_airbyte_emitted_at,
	cast(jsonb_extract_path_text(_airbyte_data, 'patient_id') as int) as patient_id,
	cast(jsonb_extract_path_text(_airbyte_data, 'goodpill_id') as int) as goodpill_id,
	cast(jsonb_extract_path_text(_airbyte_data, 'patient_date_registered') as timestamp) as patient_date_registered,
	cast(jsonb_extract_path_text(_airbyte_data, 'patient_date_added') as timestamp) as patient_date_added,
	cast(jsonb_extract_path_text(_airbyte_data, 'fill_next') as date) as fill_next,
	cast(jsonb_extract_path_text(_airbyte_data, 'days_overdue') as int) as days_overdue,
	cast(jsonb_extract_path_text(_airbyte_data, 'first_name') as varchar(255)) as first_name,
	cast(jsonb_extract_path_text(_airbyte_data, 'last_name') as varchar(255)) as last_name,
	cast(jsonb_extract_path_text(_airbyte_data, 'birth_date') as timestamp) as birth_date,
	cast(jsonb_extract_path_text(_airbyte_data, 'email') as varchar(255)) as email,
	cast(jsonb_extract_path_text(_airbyte_data, 'phone_number') as varchar(255)) as phone_number,
	cast(jsonb_extract_path_text(_airbyte_data, 'phone_number_2') as varchar(255)) as phone_number_2,
	cast(jsonb_extract_path_text(_airbyte_data, 'address') as varchar(255)) as address,
	cast(jsonb_extract_path_text(_airbyte_data, 'address_2') as varchar(255)) as address_2,
	cast(jsonb_extract_path_text(_airbyte_data, 'city') as varchar(255)) as city,
	cast(jsonb_extract_path_text(_airbyte_data, 'state') as varchar(255)) as state,
	cast(jsonb_extract_path_text(_airbyte_data, 'zip_code') as varchar(255)) as zip_code,
	cast(jsonb_extract_path_text(_airbyte_data, 'payment_card_type') as varchar(20)) as payment_card_type,
	cast(jsonb_extract_path_text(_airbyte_data, 'payment_card_last4') as varchar(4)) as payment_card_last4,
	cast(jsonb_extract_path_text(_airbyte_data, 'payment_card_date_expired') as date) as payment_card_date_expired,
	cast(jsonb_extract_path_text(_airbyte_data, 'payment_method_default') as varchar(50)) as payment_method_default,
	cast(jsonb_extract_path_text(_airbyte_data, 'payment_coupon') as varchar(20)) as payment_coupon,
	cast(jsonb_extract_path_text(_airbyte_data, 'tracking_coupon') as varchar(20)) as tracking_coupon,
	cast(jsonb_extract_path_text(_airbyte_data, 'refills_used') as decimal(5,2)) as refills_used,
	cast(jsonb_extract_path_text(_airbyte_data, 'date_processed') as timestamp) as date_processed
from "datawarehouse".raw._airbyte_raw_analytics_patients
),  __dbt__cte__an_providers as (
select
	_airbyte_ab_id,
	_airbyte_emitted_at,
	cast(jsonb_extract_path_text(_airbyte_data, 'provider_id') as int) as provider_id,
	cast(jsonb_extract_path_text(_airbyte_data, 'npi') as varchar(255)) as npi,
	cast(jsonb_extract_path_text(_airbyte_data, 'first_name') as varchar(255)) as first_name,
	cast(jsonb_extract_path_text(_airbyte_data, 'last_name') as varchar(255)) as last_name,
	cast(jsonb_extract_path_text(_airbyte_data, 'phone_number') as varchar(255)) as phone_number,
	cast(jsonb_extract_path_text(_airbyte_data, 'phone_number_2') as varchar(255)) as phone_number_2,
	cast(jsonb_extract_path_text(_airbyte_data, 'address') as varchar(255)) as address,
	cast(jsonb_extract_path_text(_airbyte_data, 'city') as varchar(255)) as city,
	cast(jsonb_extract_path_text(_airbyte_data, 'state') as varchar(255)) as state,
	cast(jsonb_extract_path_text(_airbyte_data, 'zip_code') as varchar(255)) as zip_code,
	cast(jsonb_extract_path_text(_airbyte_data, 'date_processed') as timestamp) as date_processed
from "datawarehouse".raw._airbyte_raw_analytics_providers
),  __dbt__cte__an_drugs as (
select
	_airbyte_ab_id,
	_airbyte_emitted_at,
	cast(jsonb_extract_path_text(_airbyte_data, 'drug_id') as int) as drug_id,
	cast(jsonb_extract_path_text(_airbyte_data, 'generic_name') as varchar(255)) as generic_name,
	cast(jsonb_extract_path_text(_airbyte_data, 'brand_name') as varchar(255)) as brand_name,
	cast(jsonb_extract_path_text(_airbyte_data, 'gsns') as varchar(255)) as gsns,
	cast(jsonb_extract_path_text(_airbyte_data, 'current_price_per_month') as decimal(10,4)) as current_price_per_month,
	cast(jsonb_extract_path_text(_airbyte_data, 'current_price_30') as decimal(10,4)) as current_price_30,
	cast(jsonb_extract_path_text(_airbyte_data, 'current_price_90') as decimal(10,4)) as current_price_90,
	cast(jsonb_extract_path_text(_airbyte_data, 'current_value_awp') as decimal(10,4)) as current_value_awp,
	cast(jsonb_extract_path_text(_airbyte_data, 'current_value_goodrx') as decimal(10,4)) as current_value_goodrx,
	cast(jsonb_extract_path_text(_airbyte_data, 'current_value_nadac') as decimal(10,4)) as current_value_nadac,
	cast(jsonb_extract_path_text(_airbyte_data, 'current_value_coalesced') as decimal(10,4)) as current_value_coalesced,
	cast(jsonb_extract_path_text(_airbyte_data, 'date_processed') as timestamp) as date_processed
from "datawarehouse".raw._airbyte_raw_analytics_drugs
),  __dbt__cte__an_clinics as (
select
	_airbyte_ab_id,
	_airbyte_emitted_at,
	cast(jsonb_extract_path_text(_airbyte_data, 'clinic_id') as int) as clinic_id,
	cast(jsonb_extract_path_text(_airbyte_data, 'name_clean') as varchar(255)) as name_clean,
	cast(jsonb_extract_path_text(_airbyte_data, 'name_meta') as varchar(255)) as name_meta,
	cast(jsonb_extract_path_text(_airbyte_data, 'name') as varchar(255)) as name,
	cast(jsonb_extract_path_text(_airbyte_data, 'phone_number') as varchar(255)) as phone_number,
	cast(jsonb_extract_path_text(_airbyte_data, 'phone_number_2') as varchar(255)) as phone_number_2,
	cast(jsonb_extract_path_text(_airbyte_data, 'address') as varchar(255)) as address,
	cast(jsonb_extract_path_text(_airbyte_data, 'city') as varchar(255)) as city,
	cast(jsonb_extract_path_text(_airbyte_data, 'state') as varchar(255)) as state,
	cast(jsonb_extract_path_text(_airbyte_data, 'zip_code') as varchar(255)) as zip_code,
	cast(jsonb_extract_path_text(_airbyte_data, 'date_processed') as timestamp) as date_processed
from "datawarehouse".raw._airbyte_raw_analytics_clinics
),  __dbt__cte__gp_rxs_single as (
select
    _airbyte_emitted_at,
    _airbyte_ab_id,
    cast(jsonb_extract_path_text(_airbyte_data, 'rx_number') as int) as rx_number,
    cast(jsonb_extract_path_text(_airbyte_data, 'patient_id_cp') as int) as patient_id_cp,
    cast(jsonb_extract_path_text(_airbyte_data, 'drug_generic') as varchar(255)) as drug_generic,
    cast(jsonb_extract_path_text(_airbyte_data, 'drug_brand') as varchar(255)) as drug_brand,
    cast(jsonb_extract_path_text(_airbyte_data, 'drug_name') as varchar(255)) as drug_name,
    cast(jsonb_extract_path_text(_airbyte_data, 'rx_message_key') as varchar(80)) as rx_message_key,
    cast(jsonb_extract_path_text(_airbyte_data, 'rx_message_text') as varchar(255)) as rx_message_text,
    cast(jsonb_extract_path_text(_airbyte_data, 'rx_gsn') as int) as rx_gsn,
    cast(jsonb_extract_path_text(_airbyte_data, 'drug_gsns') as varchar(255)) as drug_gsns,
    cast(jsonb_extract_path_text(_airbyte_data, 'refills_left') as decimal(5,2)) as refills_left,
    cast(jsonb_extract_path_text(_airbyte_data, 'refills_original') as decimal(5,2)) as refills_original,
    cast(jsonb_extract_path_text(_airbyte_data, 'qty_left') as decimal(10,3)) as qty_left,
    cast(jsonb_extract_path_text(_airbyte_data, 'qty_original') as decimal(10,3)) as qty_original,
    cast(jsonb_extract_path_text(_airbyte_data, 'sig_actual') as varchar(255)) as sig_actual,
    cast(jsonb_extract_path_text(_airbyte_data, 'sig_initial') as varchar(255)) as sig_initial,
    cast(jsonb_extract_path_text(_airbyte_data, 'sig_clean') as varchar(255)) as sig_clean,
    cast(jsonb_extract_path_text(_airbyte_data, 'sig_qty') as decimal(10,3)) as sig_qty,
    cast(jsonb_extract_path_text(_airbyte_data, 'sig_v1_qty') as decimal(10,3)) as sig_v1_qty,
    cast(jsonb_extract_path_text(_airbyte_data, 'sig_v1_days') as int) as sig_v1_days,
    cast(jsonb_extract_path_text(_airbyte_data, 'sig_v1_qty_per_day') as decimal(10,2)) as sig_v1_qty_per_day,
    cast(jsonb_extract_path_text(_airbyte_data, 'sig_days') as int) as sig_days,
    cast(jsonb_extract_path_text(_airbyte_data, 'sig_qty_per_day_default') as decimal(6,3)) as sig_qty_per_day_default,
    cast(jsonb_extract_path_text(_airbyte_data, 'sig_qty_per_day_actual') as decimal(6,3)) as sig_qty_per_day_actual,
    cast(jsonb_extract_path_text(_airbyte_data, 'sig_durations') as varchar(255)) as sig_durations,
    cast(jsonb_extract_path_text(_airbyte_data, 'sig_qtys_per_time') as varchar(255)) as sig_qtys_per_time,
    cast(jsonb_extract_path_text(_airbyte_data, 'sig_frequencies') as varchar(255)) as sig_frequencies,
    cast(jsonb_extract_path_text(_airbyte_data, 'sig_frequency_numerators') as varchar(255)) as sig_frequency_numerators,
    cast(jsonb_extract_path_text(_airbyte_data, 'sig_frequency_denominators') as varchar(255)) as sig_frequency_denominators,
    cast(jsonb_extract_path_text(_airbyte_data, 'sig_v2_qty') as decimal(10,3)) as sig_v2_qty,
    cast(jsonb_extract_path_text(_airbyte_data, 'sig_v2_days') as int) as sig_v2_days,
    cast(jsonb_extract_path_text(_airbyte_data, 'sig_v2_qty_per_day') as decimal(10,3)) as sig_v2_qty_per_day,
    cast(jsonb_extract_path_text(_airbyte_data, 'sig_v2_unit') as varchar(255)) as sig_v2_unit,
    cast(jsonb_extract_path_text(_airbyte_data, 'sig_v2_conf_score') as decimal(10,3)) as sig_v2_conf_score,
    cast(jsonb_extract_path_text(_airbyte_data, 'sig_v2_dosages') as varchar(255)) as sig_v2_dosages,
    cast(jsonb_extract_path_text(_airbyte_data, 'sig_v2_scores') as varchar(255)) as sig_v2_scores,
    cast(jsonb_extract_path_text(_airbyte_data, 'sig_v2_frequencies') as varchar(255)) as sig_v2_frequencies,
    cast(jsonb_extract_path_text(_airbyte_data, 'sig_v2_durations') as varchar(255)) as sig_v2_durations,
    cast(jsonb_extract_path_text(_airbyte_data, 'rx_autofill') as int) as rx_autofill,
    cast(jsonb_extract_path_text(_airbyte_data, 'refill_date_first') as timestamp) as refill_date_first,
    cast(jsonb_extract_path_text(_airbyte_data, 'refill_date_last') as timestamp) as refill_date_last,
    cast(jsonb_extract_path_text(_airbyte_data, 'refill_date_manual') as timestamp) as refill_date_manual,
    cast(jsonb_extract_path_text(_airbyte_data, 'refill_date_default') as timestamp) as refill_date_default,
    cast(jsonb_extract_path_text(_airbyte_data, 'rx_status') as int) as rx_status,
    cast(jsonb_extract_path_text(_airbyte_data, 'rx_stage') as varchar(80)) as rx_stage,
    cast(jsonb_extract_path_text(_airbyte_data, 'rx_source') as varchar(80)) as rx_source,
    cast(jsonb_extract_path_text(_airbyte_data, 'rx_transfer') as varchar(80)) as rx_transfer,
    cast(jsonb_extract_path_text(_airbyte_data, 'rx_date_transferred') as timestamp) as rx_date_transferred,
    cast(jsonb_extract_path_text(_airbyte_data, 'provider_npi') as varchar(80)) as provider_npi,
    cast(jsonb_extract_path_text(_airbyte_data, 'provider_first_name') as varchar(80)) as provider_first_name,
    cast(jsonb_extract_path_text(_airbyte_data, 'provider_last_name') as varchar(80)) as provider_last_name,
    cast(jsonb_extract_path_text(_airbyte_data, 'provider_clinic') as varchar(80)) as provider_clinic,
    cast(jsonb_extract_path_text(_airbyte_data, 'provider_phone') as varchar(10)) as provider_phone,
    cast(jsonb_extract_path_text(_airbyte_data, 'rx_date_changed') as timestamp) as rx_date_changed,
    cast(jsonb_extract_path_text(_airbyte_data, 'rx_date_expired') as timestamp) as rx_date_expired,
	cast(jsonb_extract_path_text(_airbyte_data, 'rx_date_added') as timestamp) as rx_date_added,
    cast(jsonb_extract_path_text(_airbyte_data, 'created_at') as timestamp) as created_at,
    cast(jsonb_extract_path_text(_airbyte_data, 'updated_at') as timestamp) as updated_at,
    cast(jsonb_extract_path_text(_airbyte_data, '_ab_cdc_updated_at') as timestamp) as _ab_cdc_updated_at,
    cast(jsonb_extract_path_text(_airbyte_data, '_ab_cdc_deleted_at') as timestamp) as _ab_cdc_deleted_at
from 
    "datawarehouse".raw._airbyte_raw_goodpill_gp_rxs_single
),  __dbt__cte__gp_rxs_grouped as (
select
    _airbyte_emitted_at,
    _airbyte_ab_id,
    cast(jsonb_extract_path_text(_airbyte_data, 'patient_id_cp') as int) as patient_id_cp,
    cast(jsonb_extract_path_text(_airbyte_data, 'drug_generic') as varchar(255)) as drug_generic,
    cast(jsonb_extract_path_text(_airbyte_data, 'drug_brand') as varchar(255)) as drug_brand,
    cast(jsonb_extract_path_text(_airbyte_data, 'drug_name') as varchar(255)) as drug_name,
    cast(jsonb_extract_path_text(_airbyte_data, 'sig_qty_per_day') as decimal(6,3)) as sig_qty_per_day,
    cast(jsonb_extract_path_text(_airbyte_data, 'rx_message_keys') as varchar(255)) as rx_message_keys,
    cast(jsonb_extract_path_text(_airbyte_data, 'max_gsn') as int) as max_gsn,
    cast(jsonb_extract_path_text(_airbyte_data, 'drug_gsns') as varchar(255)) as drug_gsns,
    cast(jsonb_extract_path_text(_airbyte_data, 'refills_total') as decimal(5,2)) as refills_total,
    cast(jsonb_extract_path_text(_airbyte_data, 'qty_total') as decimal(11,3)) as qty_total,
    cast(jsonb_extract_path_text(_airbyte_data, 'rx_autofill') as int) as rx_autofill,
    cast(jsonb_extract_path_text(_airbyte_data, 'refill_date_first') as timestamp) as refill_date_first,
    cast(jsonb_extract_path_text(_airbyte_data, 'refill_date_last') as timestamp) as refill_date_last,
    cast(jsonb_extract_path_text(_airbyte_data, 'refill_date_next') as timestamp) as refill_date_next,
    cast(jsonb_extract_path_text(_airbyte_data, 'refill_date_manual') as timestamp) as refill_date_manual,
    cast(jsonb_extract_path_text(_airbyte_data, 'refill_date_default') as timestamp) as refill_date_default,
    cast(jsonb_extract_path_text(_airbyte_data, 'best_rx_number') as int) as best_rx_number,
    cast(jsonb_extract_path_text(_airbyte_data, 'rx_numbers') as varchar(255)) as rx_numbers,
    cast(jsonb_extract_path_text(_airbyte_data, 'rx_sources') as varchar(80)) as rx_sources,
    cast(jsonb_extract_path_text(_airbyte_data, 'rx_date_changed') as timestamp) as rx_date_changed,
    cast(jsonb_extract_path_text(_airbyte_data, 'rx_date_expired') as timestamp) as rx_date_expired,
    cast(jsonb_extract_path_text(_airbyte_data, 'rx_date_transferred') as timestamp) as rx_date_transferred,
    cast(jsonb_extract_path_text(_airbyte_data, 'created_at') as timestamp) as created_at,
    cast(jsonb_extract_path_text(_airbyte_data, '_ab_cdc_updated_at') as timestamp) as _ab_cdc_updated_at,
    cast(jsonb_extract_path_text(_airbyte_data, '_ab_cdc_deleted_at') as timestamp) as _ab_cdc_deleted_at
from 
    "datawarehouse".raw._airbyte_raw_goodpill_gp_rxs_grouped
),  __dbt__cte__gp_patients as (
select
    _airbyte_emitted_at,
    _airbyte_ab_id,
    cast(jsonb_extract_path_text(_airbyte_data, 'patient_id_cp') as int) as patient_id_cp,
    cast(jsonb_extract_path_text(_airbyte_data, 'patient_id_wc') as int) as patient_id_wc,
    cast(jsonb_extract_path_text(_airbyte_data, 'first_name') as varchar(80)) as first_name,
    cast(jsonb_extract_path_text(_airbyte_data, 'last_name') as varchar(80)) as last_name,
    cast(jsonb_extract_path_text(_airbyte_data, 'birth_date') as timestamp) as birth_date,
    cast(jsonb_extract_path_text(_airbyte_data, 'patient_note') as varchar(3072)) as patient_note,
    cast(jsonb_extract_path_text(_airbyte_data, 'phone1') as varchar(10)) as phone1,
    cast(jsonb_extract_path_text(_airbyte_data, 'phone2') as varchar(10)) as phone2,
    cast(jsonb_extract_path_text(_airbyte_data, 'email') as varchar(255)) as email,
    cast(jsonb_extract_path_text(_airbyte_data, 'patient_autofill') as int) as patient_autofill,
    cast(jsonb_extract_path_text(_airbyte_data, 'pharmacy_name') as varchar(50)) as pharmacy_name,
    cast(jsonb_extract_path_text(_airbyte_data, 'pharmacy_npi') as varchar(10)) as pharmacy_npi,
    cast(jsonb_extract_path_text(_airbyte_data, 'pharmacy_fax') as varchar(12)) as pharmacy_fax,
    cast(jsonb_extract_path_text(_airbyte_data, 'pharmacy_phone') as varchar(12)) as pharmacy_phone,
    cast(jsonb_extract_path_text(_airbyte_data, 'pharmacy_address') as varchar(255)) as pharmacy_address,
    cast(jsonb_extract_path_text(_airbyte_data, 'payment_card_type') as varchar(20)) as payment_card_type,
    cast(jsonb_extract_path_text(_airbyte_data, 'payment_card_last4') as varchar(4)) as payment_card_last4,
    cast(jsonb_extract_path_text(_airbyte_data, 'payment_card_date_expired') as timestamp) as payment_card_date_expired,
    cast(jsonb_extract_path_text(_airbyte_data, 'payment_method_default') as varchar(50)) as payment_method_default,
    cast(jsonb_extract_path_text(_airbyte_data, 'payment_coupon') as varchar(20)) as payment_coupon,
    cast(jsonb_extract_path_text(_airbyte_data, 'tracking_coupon') as varchar(20)) as tracking_coupon,
    cast(jsonb_extract_path_text(_airbyte_data, 'patient_address1') as varchar(255)) as patient_address1,
    cast(jsonb_extract_path_text(_airbyte_data, 'patient_address2') as varchar(255)) as patient_address2,
    cast(jsonb_extract_path_text(_airbyte_data, 'patient_city') as varchar(255)) as patient_city,
    cast(jsonb_extract_path_text(_airbyte_data, 'patient_state') as varchar(2)) as patient_state,
    cast(jsonb_extract_path_text(_airbyte_data, 'patient_zip') as varchar(5)) as patient_zip,
    cast(jsonb_extract_path_text(_airbyte_data, 'refills_used') as decimal(5,2)) as refills_used,
    cast(jsonb_extract_path_text(_airbyte_data, 'patient_status') as int) as patient_status,
    cast(jsonb_extract_path_text(_airbyte_data, 'language') as varchar) as language,
    cast(jsonb_extract_path_text(_airbyte_data, 'allergies_none') as varchar(80)) as allergies_none,
    cast(jsonb_extract_path_text(_airbyte_data, 'allergies_cephalosporins') as varchar(80)) as allergies_cephalosporins,
    cast(jsonb_extract_path_text(_airbyte_data, 'allergies_sulfa') as varchar(80)) as allergies_sulfa,
    cast(jsonb_extract_path_text(_airbyte_data, 'allergies_aspirin') as varchar(80)) as allergies_aspirin,
    cast(jsonb_extract_path_text(_airbyte_data, 'allergies_penicillin') as varchar(80)) as allergies_penicillin,
    cast(jsonb_extract_path_text(_airbyte_data, 'allergies_erythromycin') as varchar(80)) as allergies_erythromycin,
    cast(jsonb_extract_path_text(_airbyte_data, 'allergies_codeine') as varchar(80)) as allergies_codeine,
    cast(jsonb_extract_path_text(_airbyte_data, 'allergies_nsaids') as varchar(80)) as allergies_nsaids,
    cast(jsonb_extract_path_text(_airbyte_data, 'allergies_salicylates') as varchar(80)) as allergies_salicylates,
    cast(jsonb_extract_path_text(_airbyte_data, 'allergies_azithromycin') as varchar(80)) as allergies_azithromycin,
    cast(jsonb_extract_path_text(_airbyte_data, 'allergies_amoxicillin') as varchar(80)) as allergies_amoxicillin,
    cast(jsonb_extract_path_text(_airbyte_data, 'allergies_tetracycline') as varchar(80)) as allergies_tetracycline,
    cast(jsonb_extract_path_text(_airbyte_data, 'allergies_other') as varchar(255)) as allergies_other,
    cast(jsonb_extract_path_text(_airbyte_data, 'medications_other') as varchar(3072)) as medications_other,
    cast(jsonb_extract_path_text(_airbyte_data, 'patient_date_added') as timestamp) as patient_date_added,
    cast(jsonb_extract_path_text(_airbyte_data, 'patient_date_registered') as timestamp) as patient_date_registered,
    cast(jsonb_extract_path_text(_airbyte_data, 'patient_date_changed') as timestamp) as patient_date_changed,
    cast(jsonb_extract_path_text(_airbyte_data, 'patient_date_updated') as timestamp) as patient_date_updated,
    cast(jsonb_extract_path_text(_airbyte_data, 'patient_inactive') as varchar) as patient_inactive,
    cast(jsonb_extract_path_text(_airbyte_data, 'patient_date_first_dispensed') as timestamp) as patient_date_first_dispensed,
    cast(jsonb_extract_path_text(_airbyte_data, 'patient_date_first_rx_received') as timestamp) as patient_date_first_rx_received,
    cast(jsonb_extract_path_text(_airbyte_data, 'patient_date_first_expected_by') as timestamp) as patient_date_first_expected_by,
    cast(jsonb_extract_path_text(_airbyte_data, '_ab_cdc_updated_at') as timestamp) as _ab_cdc_updated_at,
    cast(jsonb_extract_path_text(_airbyte_data, '_ab_cdc_deleted_at') as timestamp) as _ab_cdc_deleted_at
from
    "datawarehouse".raw._airbyte_raw_goodpill_gp_patients
),  __dbt__cte__an_patients_daily_logs as (
select
	_airbyte_ab_id,
	_airbyte_emitted_at,
	cast(jsonb_extract_path_text(_airbyte_data, 'patient_id') as int) as patient_id,
	cast(jsonb_extract_path_text(_airbyte_data, 'date_id') as int) as date_id,
	cast(jsonb_extract_path_text(_airbyte_data, 'location_id') as int) as location_id,
	cast(jsonb_extract_path_text(_airbyte_data, 'patient_log_date') as timestamp) as patient_log_date,
	cast(jsonb_extract_path_text(_airbyte_data, 'refill_date_next_max') as date) as refill_date_next_max,
	cast(jsonb_extract_path_text(_airbyte_data, 'refill_date_next_min') as date) as refill_date_next_min,
	cast(jsonb_extract_path_text(_airbyte_data, 'days_overdue') as int) as days_overdue,
	cast(jsonb_extract_path_text(_airbyte_data, 'days_lifetime') as int) as days_lifetime,
	cast(jsonb_extract_path_text(_airbyte_data, 'rxs_count') as int) as rxs_count,
	cast(jsonb_extract_path_text(_airbyte_data, 'rx_groups_count') as int) as rx_groups_count,
	cast(jsonb_extract_path_text(_airbyte_data, 'is_autofill') as int) as is_autofill,
	cast(jsonb_extract_path_text(_airbyte_data, 'refills_used_day') as int) as refills_used_day,
	cast(jsonb_extract_path_text(_airbyte_data, 'refills_used_total') as int) as refills_used_total,
	cast(jsonb_extract_path_text(_airbyte_data, 'payment_card_type') as varchar) as payment_card_type,
	cast(jsonb_extract_path_text(_airbyte_data, 'payment_card_last4') as varchar) as payment_card_last4,
	cast(jsonb_extract_path_text(_airbyte_data, 'payment_card_date_expired') as date) as payment_card_date_expired,
	cast(jsonb_extract_path_text(_airbyte_data, 'payment_method_default') as varchar) as payment_method_default,
	cast(jsonb_extract_path_text(_airbyte_data, 'payment_coupon') as varchar) as payment_coupon,
	cast(jsonb_extract_path_text(_airbyte_data, 'tracking_coupon') as varchar) as tracking_coupon,
	cast(jsonb_extract_path_text(_airbyte_data, 'modified_by') as varchar) as modified_by,
	cast(jsonb_extract_path_text(_airbyte_data, 'date_processed') as timestamp) as date_processed
from "datawarehouse".raw._airbyte_raw_analytics_patients_daily_logs
),  __dbt__cte__an_dates as (
select
	cast(jsonb_extract_path_text(_airbyte_data, 'date_id') as int) as date_id,
	cast(jsonb_extract_path_text(_airbyte_data, 'db_date') as date) as db_date,
	cast(jsonb_extract_path_text(_airbyte_data, 'year') as int) as year,
	cast(jsonb_extract_path_text(_airbyte_data, 'month') as int) as month,
	cast(jsonb_extract_path_text(_airbyte_data, 'day') as int) as day,
	cast(jsonb_extract_path_text(_airbyte_data, 'week_of_year') as int) as week_of_year,
	cast(jsonb_extract_path_text(_airbyte_data, 'month_name') as varchar) as month_name,
	cast(jsonb_extract_path_text(_airbyte_data, 'day_name') as varchar) as day_name,
	cast(jsonb_extract_path_text(_airbyte_data, 'holiday_flag') as int) as holiday_flag,
	cast(jsonb_extract_path_text(_airbyte_data, 'weekend_flag') as int) as weekend_flag,
	cast(jsonb_extract_path_text(_airbyte_data, 'quarter') as int) as quarter,
	cast(jsonb_extract_path_text(_airbyte_data, 'semester') as int) as semester,
	cast(jsonb_extract_path_text(_airbyte_data, 'date_processed') as timestamp) as date_processed
from "datawarehouse".raw._airbyte_raw_analytics_dates
),  __dbt__cte__an_times as (
select
	cast(jsonb_extract_path_text(_airbyte_data, 'time_id') as int) as time_id,
	cast(jsonb_extract_path_text(_airbyte_data, 'hour24') as int) as hour24,
	cast(jsonb_extract_path_text(_airbyte_data, 'hour24_string') as varchar) as hour24_string,
	cast(jsonb_extract_path_text(_airbyte_data, 'hour12') as int) as hour12,
	cast(jsonb_extract_path_text(_airbyte_data, 'hour12_string') as varchar) as hour12_string,
	cast(jsonb_extract_path_text(_airbyte_data, 'minute') as int) as minute,
	cast(jsonb_extract_path_text(_airbyte_data, 'minute_string') as varchar) as minute_string,
	cast(jsonb_extract_path_text(_airbyte_data, 'second') as int) as second,
	cast(jsonb_extract_path_text(_airbyte_data, 'second_string') as varchar) as second_string,
	cast(jsonb_extract_path_text(_airbyte_data, 'hour24_min_string') as varchar) as hour24_min_string,
	cast(jsonb_extract_path_text(_airbyte_data, 'hour24_full_string') as varchar) as hour24_full_string,
	cast(jsonb_extract_path_text(_airbyte_data, 'hour12_min_string') as varchar) as hour12_min_string,
	cast(jsonb_extract_path_text(_airbyte_data, 'hour12_full_string') as varchar) as hour12_full_string,
	cast(jsonb_extract_path_text(_airbyte_data, 'ampm_code') as int) as ampm_code,
	cast(jsonb_extract_path_text(_airbyte_data, 'ampm_string') as varchar) as ampm_string
from "datawarehouse".raw._airbyte_raw_analytics_times
),rxh as (

	with pdl as (
		select
			p.goodpill_id as patient_id_cp,
			pdl.refill_date_next_max,
			d.db_date
		from __dbt__cte__an_patients_daily_logs pdl
		inner join __dbt__cte__an_patients p using (patient_id)
		inner join __dbt__cte__an_dates d using (date_id)
	)
	select
		fl.*,
		case
			when event_type = 'WRITTEN' or event_type = 'TRANSFERRED' then concat('RX_', event_type)
			else 'RX_UPDATED'
		end as event_name,
		coalesce(concat(dts.db_date, 'T', tms.hour24_full_string)::timestamp,  goodpill_event_date) as event_date,
		prv.npi as provider_npi,
		cli.name as clinic_name,
		pat.goodpill_id as patient_id_cp,
		drg.generic_name as drug_generic,
		pdl.refill_date_next_max,
		null::timestamp as _ab_cdc_updated_at,
		'ANALYTICS_V1' as _airbyte_source
	from __dbt__cte__an_fills_logs fl
	left join __dbt__cte__an_patients pat using (patient_id)
	left join __dbt__cte__an_providers prv using (provider_id)
	left join __dbt__cte__an_drugs drg using (drug_id)
	left join __dbt__cte__an_clinics cli using (clinic_id)
	left join __dbt__cte__an_dates dts on dts.date_id = fl.event_date_id
	left join __dbt__cte__an_times tms on tms.time_id = fl.event_time_id
	left join pdl on pdl.db_date = dts.db_date and pdl.patient_id_cp = pat.goodpill_id
	where event_type <> 'REMOVED' or event_type <> 'DISPENSED'



)
select
	rx_number,
	patient_id_cp,
	drug_generic,
	clinic_name,
	provider_npi,
	is_refill,
	rx_autofill,
	sig_qty_per_day,
	rx_message_key,
	max_gsn,
	drug_gsns,
	refills_total,
	refills_original,
	refills_left,
	refill_date_first,
	refill_date_last,
	rx_date_expired,
	rx_date_changed,
	qty_left,
	qty_original,
	sig_actual,
	sig_initial,
	sig_clean,
	sig_qty,
	sig_days,
	sig_qty_per_day_actual,
	sig_v2_qty,
	sig_v2_days,
	sig_v2_qty_per_day,
	sig_v2_unit,
	sig_v2_conf_score,
	sig_v2_dosages,
	sig_v2_scores,
	sig_v2_frequencies,
	sig_v2_durations,
	coalesce(refill_date_next_max, refill_date_next) as refill_date_next,
	refill_date_manual,
	refill_date_default,
	qty_total,
	rx_source,
	rx_transfer,
	event_name,
	event_date,
	_airbyte_ab_id,
	_airbyte_emitted_at as _airbyte_emitted_at,
	_ab_cdc_updated_at as _ab_cdc_updated_at,
	_airbyte_source,
	md5(cast(event_name || rx_number || event_date as 
    varchar
)) as unique_event_id
from rxh