with qb_gp_union as (
	select
		order_invoice_number,
		patient_id_cp,
		rx_number,
		dwh_patient_event_date,
		dwh_patient_status,
		patient_date_active,
		patient_date_no_rx,
		patient_date_unregistered,
		patient_date_deceased,
		patient_date_churned_no_fillable_rx,
		patient_date_inactive,
		patient_date_churned_other,
		patient_clinic_name_coupon,
		rx_numbers,
		rx_best_rx_number,
		rx_provider_npi,
		rx_drug_generic,
		rx_drug_brand,
		rx_drug_name,
		rx_message_key,
		rx_message_text,
		rx_gsn,
		rx_drug_gsns,
		rx_max_gsn,
		rx_refills_left,
		rx_refills_original,
		rx_refills_total,
		rx_qty_left,
		rx_qty_original,
		rx_sig_actual,
		rx_sig_initial,
		rx_sig_clean,
		rx_sig_qty,
		rx_sig_v1_qty,
		rx_sig_v1_days,
		rx_sig_v1_qty_per_day,
		rx_sig_days,
		rx_sig_qty_per_day,
		rx_sig_qty_per_day_default,
		rx_sig_qty_per_day_actual,
		rx_sig_durations,
		rx_sig_qtys_per_time,
		rx_sig_frequencies,
		rx_sig_frequency_numerators,
		rx_sig_frequency_denominators,
		rx_sig_v2_qty,
		rx_sig_v2_days,
		rx_sig_v2_qty_per_day,
		rx_sig_v2_unit,
		rx_sig_v2_conf_score,
		rx_sig_v2_dosages,
		rx_sig_v2_scores,
		rx_sig_v2_frequencies,
		rx_sig_v2_durations,
		rx_autofill,
		rx_refill_date_first,
		rx_refill_date_last,
		rx_refill_date_manual,
		rx_refill_date_next,
		rx_status,
		rx_stage,
		rx_source,
		rx_transfer,
		rx_date_transferred,
		provider_first_name,
		provider_last_name,
		provider_phone,
		rx_clinic_name,
		rx_date_changed,
		rx_date_expired,
		rx_date_added,
		rx_created_at,
		rx_updated_at,
		group_created_at,

		rx_clinic_name_cp,
		item_groups,
		item_rx_dispensed_id,
		item_stock_level_initial,
		item_rx_message_keys_initial,
		item_patient_autofill_initial,
		item_rx_autofill_initial,
		item_rx_numbers_initial,
		item_zscore_initial,
		item_refills_dispensed_default,
		item_refills_dispensed_actual,
		item_days_dispensed_default,
		item_days_dispensed_actual,
		item_qty_dispensed_default,
		item_qty_dispensed_actual,
		item_price_dispensed_default,
		item_price_dispensed_actual,
		item_qty_pended_total,
		item_qty_pended_repacks,
		item_count_pended_total,
		item_count_pended_repacks,
		item_message_keys,
		item_message_text,
		item_type,
		item_added_by,
		item_date_added,
		item_date_changed,
		item_date_updated,
		item_refill_date_last,
		item_refill_date_manual,
		item_refill_date_default,
		item_refill_target_date,
		item_refill_target_days,
		item_refill_target_rxs,
		item_add_user_id,
		item_chg_user_id,
		item_count_lines,
		patient_id_wc,
		order_date_added,
		order_date_dispensed,
		order_date_shipped,
		order_date_returned,
		order_count_items,
		order_count_filled,
		order_count_nofill,
		order_source,
		order_stage_cp,
		order_stage_wc,
		order_status,
		order_address1,
		order_address2,
		order_invoice_doc_id,
		order_tracking_number,
		order_payment_total_default,
		order_payment_total_actual,
		order_payment_fee_default,
		order_payment_fee_actual,
		order_payment_due_default,
		order_payment_due_actual,
		order_payment_date_autopay,
		order_payment_method_actual,
		order_payment_coupon,
		order_date_delivered,
		order_date_expedited,
		order_date_expected,
		order_date_expected_initial,
		order_date_failed,
		order_add_user_id,
		order_chg_user_id,
		order_shipping_speed,
		order_note,
		order_rph_check,
		order_tech_fill,
		order_city,
		order_state,
		order_zip,
		order_date_updated,
		clinic_coalesced_name,
		dwh_updated_at,
		clinic_name_cp,
		clinic_rx_date_added_first,
		clinic_rx_date_added_last,
		clinic_verified,
		dw_clinic_id,
		dw_clinic_name_cp,
		dw_clinic_address,
		dw_clinic_street,
		dw_clinic_city,
		dw_clinic_state,
		dw_clinic_zip,
		dw_clinic_phone,
		dw_clinic_id_sf,
		dw_clinic_group_id,
		dw_clinic_group_name,
		dw_clinic_group_id_sf,
		dw_clinic_group_domain,
		drug_brand,
		drug_gsns,
		drug_price30,
		drug_price90,
		drug_price_retail,
		drug_price_goodrx,
		drug_price_nadac,
		drug_price_coalesced,
		drug_qty_repack,
		drug_count_ndcs,
		provider_id,
		provider_verified,
		provider_first_rx_sent_date,
		provider_last_rx_sent_date,
		dw_provider_name,
		dw_provider_phone,
		dw_provider_id_sf,
		patient_date_registered,
		patient_date_added,
		patient_first_name,
		patient_last_name,
		patient_birth_date,
		patient_language,
		patient_phone1,
		patient_phone2,
		patient_address,
		patient_city,
		patient_state,
		patient_zip,
		patient_payment_card_type,
		patient_payment_card_last4,
		patient_payment_card_date_expired,
		patient_payment_method_default,
		patient_date_first_rx_received,
		patient_date_first_dispensed,
		patient_date_first_expected_by,
		patient_refills_used,
		patient_email,
		patient_autofill,
		patient_initial_invoice_number,
		patient_note,
		patient_allergies_none,
		patient_allergies_cephalosporins,
		patient_allergies_sulfa,
		patient_allergies_aspirin,
		patient_allergies_penicillin,
		patient_allergies_erythromycin,
		patient_allergies_codeine,
		patient_allergies_nsaids,
		patient_allergies_salicylates,
		patient_allergies_azithromycin,
		patient_allergies_amoxicillin,
		patient_allergies_tetracycline,
		patient_allergies_other,
		patient_medications_other,
		pharmacy_npi,
		pharmacy_name,
		pharmacy_phone,
		pharmacy_fax,
		pharmacy_address,
		patient_payment_coupon,
		patient_tracking_coupon,
		null::date as transaction_date,
		null::numeric as qbo_amount,
		null::varchar as qbo_account_sub,
		null::varchar as qbo_account_full,
		null::varchar as qbo_account_top,
		null::varchar as qbo_report_type,
		null::varchar as qbo_account_type,
		null::varchar as qbo_account_classification,
		null::varchar as qbo_account_number
	from "datawarehouse".dev_analytics."goodpill_snapshot_abt"
	
	union all
	
	select
		null::integer as order_invoice_number,
		null::integer as patient_id_cp,
		null::integer as rx_number,
		null::timestamp as dwh_patient_event_date,
		null::text as dwh_patient_status,
		null::timestamp as patient_date_active,
		null::timestamp as patient_date_no_rx,
		null::timestamp as patient_date_unregistered,
		null::timestamp as patient_date_deceased,
		null::timestamp as patient_date_churned_no_fillable_rx,
		null::timestamp as patient_date_inactive,
		null::timestamp as patient_date_churned_other,
		null::text as patient_clinic_name_coupon,
		null::text as rx_numbers,
		null::integer as rx_best_rx_number,
		null::text as rx_provider_npi,
		null::text as rx_drug_generic,
		null::text as rx_drug_brand,
		null::text as rx_drug_name,
		null::text as rx_message_key,
		null::text as rx_message_text,
		null::integer as rx_gsn,
		null::text as rx_drug_gsns,
		null::integer as rx_max_gsn,
		null::numeric as rx_refills_left,
		null::numeric as rx_refills_original,
		null::numeric as rx_refills_total,
		null::numeric as rx_qty_left,
		null::numeric as rx_qty_original,
		null::text as rx_sig_actual,
		null::text as rx_sig_initial,
		null::text as rx_sig_clean,
		null::numeric as rx_sig_qty,
		null::numeric as rx_sig_v1_qty,
		null::integer as rx_sig_v1_days,
		null::numeric as rx_sig_v1_qty_per_day,
		null::integer as rx_sig_days,
		null::numeric as rx_sig_qty_per_day,
		null::numeric as rx_sig_qty_per_day_default,
		null::numeric as rx_sig_qty_per_day_actual,
		null::text as rx_sig_durations,
		null::text as rx_sig_qtys_per_time,
		null::text as rx_sig_frequencies,
		null::text as rx_sig_frequency_numerators,
		null::text as rx_sig_frequency_denominators,
		null::numeric as rx_sig_v2_qty,
		null::integer as rx_sig_v2_days,
		null::numeric as rx_sig_v2_qty_per_day,
		null::text as rx_sig_v2_unit,
		null::numeric as rx_sig_v2_conf_score,
		null::text as rx_sig_v2_dosages,
		null::text as rx_sig_v2_scores,
		null::text as rx_sig_v2_frequencies,
		null::text as rx_sig_v2_durations,
		null::integer as rx_autofill,
		null::timestamp as rx_refill_date_first,
		null::timestamp as rx_refill_date_last,
		null::timestamp as rx_refill_date_manual,
		null::timestamp as rx_refill_date_next,
		null::integer as rx_status,
		null::text as rx_stage,
		null::text as rx_source,
		null::text as rx_transfer,
		null::timestamp as rx_date_transferred,
		null::text as provider_first_name,
		null::text as provider_last_name,
		null::text as provider_phone,
		null::text as rx_clinic_name,
		null::timestamp as rx_date_changed,
		null::timestamp as rx_date_expired,
		null::timestamp as rx_date_added,
		null::timestamp as rx_created_at,
		null::timestamp as rx_updated_at,
		null::timestamp as group_created_at,
		null::text as rx_clinic_name_cp,
		null::text as item_groups,
		null::integer as item_rx_dispensed_id,
		null::text as item_stock_level_initial,
		null::text as item_rx_message_keys_initial,
		null::integer as item_patient_autofill_initial,
		null::integer as item_rx_autofill_initial,
		null::text as item_rx_numbers_initial,
		null::numeric as item_zscore_initial,
		null::numeric as item_refills_dispensed_default,
		null::numeric as item_refills_dispensed_actual,
		null::integer as item_days_dispensed_default,
		null::integer as item_days_dispensed_actual,
		null::numeric as item_qty_dispensed_default,
		null::numeric as item_qty_dispensed_actual,
		null::numeric as item_price_dispensed_default,
		null::numeric as item_price_dispensed_actual,
		null::numeric as item_qty_pended_total,
		null::numeric as item_qty_pended_repacks,
		null::integer as item_count_pended_total,
		null::integer as item_count_pended_repacks,
		null::text as item_message_keys,
		null::text as item_message_text,
		null::text as item_type,
		null::text as item_added_by,
		null::timestamp as item_date_added,
		null::timestamp as item_date_changed,
		null::timestamp as item_date_updated,
		null::timestamp as item_refill_date_last,
		null::timestamp as item_refill_date_manual,
		null::timestamp as item_refill_date_default,
		null::timestamp as item_refill_target_date,
		null::integer as item_refill_target_days,
		null::text as item_refill_target_rxs,
		null::integer as item_add_user_id,
		null::integer as item_chg_user_id,
		null::integer as item_count_lines,
		null::integer as patient_id_wc,
		null::timestamp as order_date_added,
		null::timestamp as order_date_dispensed,
		null::timestamp as order_date_shipped,
		null::timestamp as order_date_returned,
		null::integer as order_count_items,
		null::integer as order_count_filled,
		null::integer as order_count_nofill,
		null::text as order_source,
		null::text as order_stage_cp,
		null::text as order_stage_wc,
		null::text as order_status,
		null::text as order_address1,
		null::text as order_address2,
		null::text as order_invoice_doc_id,
		null::text as order_tracking_number,
		null::integer as order_payment_total_default,
		null::integer as order_payment_total_actual,
		null::integer as order_payment_fee_default,
		null::integer as order_payment_fee_actual,
		null::integer as order_payment_due_default,
		null::integer as order_payment_due_actual,
		null::text as order_payment_date_autopay,
		null::text as order_payment_method_actual,
		null::text as order_payment_coupon,
		null::timestamp as order_date_delivered,
		null::timestamp as order_date_expedited,
		null::timestamp as order_date_expected,
		null::timestamp as order_date_expected_initial,
		null::timestamp as order_date_failed,
		null::integer as order_add_user_id,
		null::integer as order_chg_user_id,
		null::integer as order_shipping_speed,
		null::text as order_note,
		null::text as order_rph_check,
		null::text as order_tech_fill,
		null::text as order_city,
		null::text as order_state,
		null::text as order_zip,
		null::timestamp as order_date_updated,
		null::text as clinic_coalesced_name,
		null::timestamp as dwh_updated_at,
		null::text as clinic_name_cp,
		null::timestamp as clinic_rx_date_added_first,
		null::timestamp as clinic_rx_date_added_last,
		null::boolean as clinic_verified,
		null::integer as dw_clinic_id,
		null::text as dw_clinic_name_cp,
		null::text as dw_clinic_address,
		null::text as dw_clinic_street,
		null::text as dw_clinic_city,
		null::text as dw_clinic_state,
		null::text as dw_clinic_zip,
		null::text as dw_clinic_phone,
		null::text as dw_clinic_id_sf,
		null::integer as dw_clinic_group_id,
		null::text as dw_clinic_group_name,
		null::text as dw_clinic_group_id_sf,
		null::text as dw_clinic_group_domain,
		null::text as drug_brand,
		null::text as drug_gsns,
		null::integer as drug_price30,
		null::integer as drug_price90,
		null::numeric as drug_price_retail,
		null::numeric as drug_price_goodrx,
		null::numeric as drug_price_nadac,
		null::numeric as drug_price_coalesced,
		null::integer as drug_qty_repack,
		null::integer as drug_count_ndcs,
		null::integer as provider_id,
		null::boolean as provider_verified,
		null::timestamp as provider_first_rx_sent_date,
		null::timestamp as provider_last_rx_sent_date,
		null::text as dw_provider_name,
		null::text as dw_provider_phone,
		null::text as dw_provider_id_sf,
		null::timestamp as patient_date_registered,
		null::timestamp as patient_date_added,
		null::text as patient_first_name,
		null::text as patient_last_name,
		null::timestamp as patient_birth_date,
		null::timestamp as patient_language,
		null::text as patient_phone1,
		null::text as patient_phone2,
		null::text as patient_address,
		null::text as patient_city,
		null::text as patient_state,
		null::text as patient_zip,
		null::text as patient_payment_card_type,
		null::text as patient_payment_card_last4,
		null::timestamp as patient_payment_card_date_expired,
		null::text as patient_payment_method_default,
		null::timestamp as patient_date_first_rx_received,
		null::timestamp as patient_date_first_dispensed,
		null::timestamp as patient_date_first_expected_by,
		null::numeric as patient_refills_used,
		null::text as patient_email,
		null::integer as patient_autofill,
		null::integer as patient_initial_invoice_number,
		null::text as patient_note,
		null::text as patient_allergies_none,
		null::text as patient_allergies_cephalosporins,
		null::text as patient_allergies_sulfa,
		null::text as patient_allergies_aspirin,
		null::text as patient_allergies_penicillin,
		null::text as patient_allergies_erythromycin,
		null::text as patient_allergies_codeine,
		null::text as patient_allergies_nsaids,
		null::text as patient_allergies_salicylates,
		null::text as patient_allergies_azithromycin,
		null::text as patient_allergies_amoxicillin,
		null::text as patient_allergies_tetracycline,
		null::text as patient_allergies_other,
		null::text as patient_medications_other,
		null::text as pharmacy_npi,
		null::text as pharmacy_name,
		null::text as pharmacy_phone,
		null::text as pharmacy_fax,
		null::text as pharmacy_address,
		null::text as patient_payment_coupon,
		null::text as patient_tracking_coupon,
		date(transaction_date) as transaction_date,
		adjusted_amount as qbo_amount,
		account_name as qbo_account_sub,
		account_fully_qualified_name as qbo_account_full,
		top_level_account_name as qbo_account_top,
		financial_statement_helper  as qbo_report_type,
		account_type as qbo_account_type,
		account_classification as qbo_account_classification,
		account_number as qbo_account_number
	from "datawarehouse".dev_quickbooks."general_ledger_abt"
)
select
	order_invoice_number,
	patient_id_cp,
	rx_number,
	coalesce(date(dwh_patient_event_date), transaction_date) as dwh_patient_event_date,
	dwh_patient_status,
	coalesce(date(patient_date_active), transaction_date) as patient_date_active,
	coalesce(date(patient_date_no_rx), transaction_date) as patient_date_no_rx,
	coalesce(date(patient_date_unregistered), transaction_date) as patient_date_unregistered,
	coalesce(date(patient_date_deceased), transaction_date) as patient_date_deceased,
	coalesce(date(patient_date_churned_no_fillable_rx), transaction_date) as patient_date_churned_no_fillable_rx,
	coalesce(date(patient_date_inactive), transaction_date) as patient_date_inactive,
	coalesce(date(patient_date_churned_other), transaction_date) as patient_date_churned_other,
	patient_clinic_name_coupon,
	rx_numbers,
	rx_best_rx_number,
	rx_provider_npi,
	rx_drug_generic,
	rx_drug_brand,
	rx_drug_name,
	rx_message_key,
	rx_message_text,
	rx_gsn,
	rx_drug_gsns,
	rx_max_gsn,
	rx_refills_left,
	rx_refills_original,
	rx_refills_total,
	rx_qty_left,
	rx_qty_original,
	rx_sig_actual,
	rx_sig_initial,
	rx_sig_clean,
	rx_sig_qty,
	rx_sig_v1_qty,
	rx_sig_v1_days,
	rx_sig_v1_qty_per_day,
	rx_sig_days,
	rx_sig_qty_per_day,
	rx_sig_qty_per_day_default,
	rx_sig_qty_per_day_actual,
	rx_sig_durations,
	rx_sig_qtys_per_time,
	rx_sig_frequencies,
	rx_sig_frequency_numerators,
	rx_sig_frequency_denominators,
	rx_sig_v2_qty,
	rx_sig_v2_days,
	rx_sig_v2_qty_per_day,
	rx_sig_v2_unit,
	rx_sig_v2_conf_score,
	rx_sig_v2_dosages,
	rx_sig_v2_scores,
	rx_sig_v2_frequencies,
	rx_sig_v2_durations,
	rx_autofill,
	coalesce(date(rx_refill_date_first), transaction_date) as rx_refill_date_first,
	coalesce(date(rx_refill_date_last), transaction_date) as rx_refill_date_last,
	coalesce(date(rx_refill_date_manual), transaction_date) as rx_refill_date_manual,
	coalesce(date(rx_refill_date_next), transaction_date) as rx_refill_date_next,
	rx_status,
	rx_stage,
	rx_source,
	rx_transfer,
	coalesce(date(rx_date_transferred), transaction_date) as rx_date_transferred,
	provider_first_name,
	provider_last_name,
	provider_phone,
	rx_clinic_name,
	coalesce(date(rx_date_changed), transaction_date) as rx_date_changed,
	coalesce(date(rx_date_expired), transaction_date) as rx_date_expired,
	coalesce(date(rx_date_added), transaction_date) as rx_date_added,
	rx_created_at,
	rx_updated_at,
	group_created_at,
	rx_clinic_name_cp,
	item_groups,
	item_rx_dispensed_id,
	item_stock_level_initial,
	item_rx_message_keys_initial,
	item_patient_autofill_initial,
	item_rx_autofill_initial,
	item_rx_numbers_initial,
	item_zscore_initial,
	item_refills_dispensed_default,
	item_refills_dispensed_actual,
	item_days_dispensed_default,
	item_days_dispensed_actual,
	item_qty_dispensed_default,
	item_qty_dispensed_actual,
	item_price_dispensed_default,
	item_price_dispensed_actual,
	item_qty_pended_total,
	item_qty_pended_repacks,
	item_count_pended_total,
	item_count_pended_repacks,
	item_message_keys,
	item_message_text,
	item_type,
	item_added_by,
	coalesce(date(item_date_added), transaction_date) as item_date_added,
	coalesce(date(item_date_changed), transaction_date) as item_date_changed,
	coalesce(date(item_date_updated), transaction_date) as item_date_updated,
	coalesce(date(item_refill_date_last), transaction_date) as item_refill_date_last,
	coalesce(date(item_refill_date_manual), transaction_date) as item_refill_date_manual,
	coalesce(date(item_refill_date_default), transaction_date) as item_refill_date_default,
	coalesce(date(item_refill_target_date), transaction_date) as item_refill_target_date,
	item_refill_target_days,
	item_refill_target_rxs,
	item_add_user_id,
	item_chg_user_id,
	item_count_lines,
	patient_id_wc,
	coalesce(date(order_date_added), transaction_date) as order_date_added,
	coalesce(date(order_date_dispensed), transaction_date) as order_date_dispensed,
	coalesce(date(order_date_shipped), transaction_date) as order_date_shipped,
	coalesce(date(order_date_returned), transaction_date) as order_date_returned,
	order_count_items,
	order_count_filled,
	order_count_nofill,
	order_source,
	order_stage_cp,
	order_stage_wc,
	order_status,
	order_address1,
	order_address2,
	order_invoice_doc_id,
	order_tracking_number,
	order_payment_total_default,
	order_payment_total_actual,
	order_payment_fee_default,
	order_payment_fee_actual,
	order_payment_due_default,
	order_payment_due_actual,
	order_payment_date_autopay,
	order_payment_method_actual,
	order_payment_coupon,
	coalesce(date(order_date_delivered), transaction_date) as order_date_delivered,
	coalesce(date(order_date_expedited), transaction_date) as order_date_expedited,
	coalesce(date(order_date_expected), transaction_date) as order_date_expected,
	coalesce(date(order_date_expected_initial), transaction_date) as order_date_expected_initial,
	coalesce(date(order_date_failed), transaction_date) as order_date_failed,
	order_add_user_id,
	order_chg_user_id,
	order_shipping_speed,
	order_note,
	order_rph_check,
	order_tech_fill,
	order_city,
	order_state,
	order_zip,
	coalesce(date(order_date_updated), transaction_date) as order_date_updated,
	clinic_coalesced_name,
	dwh_updated_at,
	clinic_name_cp,
	coalesce(date(clinic_rx_date_added_first), transaction_date) as clinic_rx_date_added_first,
	coalesce(date(clinic_rx_date_added_last), transaction_date) as clinic_rx_date_added_last,
	clinic_verified,
	dw_clinic_id,
	dw_clinic_name_cp,
	dw_clinic_address,
	dw_clinic_street,
	dw_clinic_city,
	dw_clinic_state,
	dw_clinic_zip,
	dw_clinic_phone,
	dw_clinic_id_sf,
	dw_clinic_group_id,
	dw_clinic_group_name,
	dw_clinic_group_id_sf,
	dw_clinic_group_domain,
	drug_brand,
	drug_gsns,
	drug_price30,
	drug_price90,
	drug_price_retail,
	drug_price_goodrx,
	drug_price_nadac,
	drug_price_coalesced,
	drug_qty_repack,
	drug_count_ndcs,
	provider_id,
	provider_verified,
	coalesce(date(provider_first_rx_sent_date), transaction_date) as provider_first_rx_sent_date,
	coalesce(date(provider_last_rx_sent_date), transaction_date) as provider_last_rx_sent_date,
	dw_provider_name,
	dw_provider_phone,
	dw_provider_id_sf,
	coalesce(date(patient_date_registered), transaction_date) as patient_date_registered,
	coalesce(date(patient_date_added), transaction_date) as patient_date_added,
	patient_first_name,
	patient_last_name,
	coalesce(date(patient_birth_date), transaction_date) as patient_birth_date,
	patient_language,
	patient_phone1,
	patient_phone2,
	patient_address,
	patient_city,
	patient_state,
	patient_zip,
	patient_payment_card_type,
	patient_payment_card_last4,
	coalesce(date(patient_payment_card_date_expired), transaction_date) as patient_payment_card_date_expired,
	patient_payment_method_default,
	coalesce(date(patient_date_first_rx_received), transaction_date) as patient_date_first_rx_received,
	coalesce(date(patient_date_first_dispensed), transaction_date) as patient_date_first_dispensed,
	coalesce(date(patient_date_first_expected_by), transaction_date) as patient_date_first_expected_by,
	patient_refills_used,
	patient_email,
	patient_autofill,
	patient_initial_invoice_number,
	patient_note,
	patient_allergies_none,
	patient_allergies_cephalosporins,
	patient_allergies_sulfa,
	patient_allergies_aspirin,
	patient_allergies_penicillin,
	patient_allergies_erythromycin,
	patient_allergies_codeine,
	patient_allergies_nsaids,
	patient_allergies_salicylates,
	patient_allergies_azithromycin,
	patient_allergies_amoxicillin,
	patient_allergies_tetracycline,
	patient_allergies_other,
	patient_medications_other,
	pharmacy_npi,
	pharmacy_name,
	pharmacy_phone,
	pharmacy_fax,
	pharmacy_address,
	patient_payment_coupon,
	patient_tracking_coupon,
	transaction_date,
	qbo_amount,
	qbo_account_sub,
	qbo_account_full,
	qbo_account_top,
	qbo_report_type,
	qbo_account_type,
	qbo_account_classification,
	qbo_account_number
from
	qb_gp_union