select
	_airbyte_ab_id,
	_airbyte_emitted_at,
	cast(jsonb_extract_path_text(_airbyte_data, 'invoice_number') as int) as invoice_number,
	cast(jsonb_extract_path_text(_airbyte_data, 'patient_id') as int) as patient_id,
	cast(jsonb_extract_path_text(_airbyte_data, 'event_date_id') as int) as event_date_id,
	cast(jsonb_extract_path_text(_airbyte_data, 'event_time_id') as int) as event_time_id,
	cast(jsonb_extract_path_text(_airbyte_data, 'location_id') as int) as location_id,
	cast(jsonb_extract_path_text(_airbyte_data, 'event_type') as varchar(15)) as event_type,
	cast(jsonb_extract_path_text(_airbyte_data, 'goodpill_event_date') as timestamp) as goodpill_event_date,
	cast(jsonb_extract_path_text(_airbyte_data, 'count_items') as int) as count_items,
	cast(jsonb_extract_path_text(_airbyte_data, 'count_filled') as int) as count_filled,
	cast(jsonb_extract_path_text(_airbyte_data, 'count_nofill') as int) as count_nofill,
	cast(jsonb_extract_path_text(_airbyte_data, 'order_source') as varchar(80)) as order_source,
	cast(jsonb_extract_path_text(_airbyte_data, 'order_stage_cp') as varchar(80)) as order_stage_cp,
	cast(jsonb_extract_path_text(_airbyte_data, 'order_status') as varchar(80)) as order_status,
	cast(jsonb_extract_path_text(_airbyte_data, 'invoice_doc_id') as varchar(80)) as invoice_doc_id,
	cast(jsonb_extract_path_text(_airbyte_data, 'tracking_number') as varchar(80)) as tracking_number,
	cast(jsonb_extract_path_text(_airbyte_data, 'order_date_changed') as timestamp) as order_date_changed,
	cast(jsonb_extract_path_text(_airbyte_data, 'order_date_updated') as timestamp) as order_date_updated,
	cast(jsonb_extract_path_text(_airbyte_data, 'payment_total_default') as int) as payment_total_default,
	cast(jsonb_extract_path_text(_airbyte_data, 'payment_total_actual') as int) as payment_total_actual,
	cast(jsonb_extract_path_text(_airbyte_data, 'payment_fee_default') as int) as payment_fee_default,
	cast(jsonb_extract_path_text(_airbyte_data, 'payment_fee_actual') as int) as payment_fee_actual,
	cast(jsonb_extract_path_text(_airbyte_data, 'payment_due_default') as int) as payment_due_default,
	cast(jsonb_extract_path_text(_airbyte_data, 'payment_due_actual') as int) as payment_due_actual,
	cast(jsonb_extract_path_text(_airbyte_data, 'payment_date_autopay') as varchar(80)) as payment_date_autopay,
	cast(jsonb_extract_path_text(_airbyte_data, 'payment_method_actual') as varchar(80)) as payment_method_actual,
	cast(jsonb_extract_path_text(_airbyte_data, 'coupon_lines') as varchar(255)) as coupon_lines,
	cast(jsonb_extract_path_text(_airbyte_data, 'order_note') as text) as order_note,
	cast(jsonb_extract_path_text(_airbyte_data, 'rph_check') as varchar(5)) as rph_check,
	cast(jsonb_extract_path_text(_airbyte_data, 'tech_fill') as varchar(5)) as tech_fill,
	cast(jsonb_extract_path_text(_airbyte_data, 'date_processed') as timestamp) as date_processed
from "datawarehouse".raw._airbyte_raw_analytics_orders_logs