select
	_airbyte_ab_id,
	_airbyte_emitted_at,
	cast(jsonb_extract_path_text(_airbyte_data, 'patient_id') as int) as patient_id,
	cast(jsonb_extract_path_text(_airbyte_data, 'date_id') as int) as date_id,
	cast(jsonb_extract_path_text(_airbyte_data, 'location_id') as int) as location_id,
	cast(jsonb_extract_path_text(_airbyte_data, 'patient_log_date') as timestamp) as patient_log_date,
	cast(jsonb_extract_path_text(_airbyte_data, 'refill_date_next_max') as date) as refill_date_next_max,
	cast(jsonb_extract_path_text(_airbyte_data, 'refill_date_next_min') as date) as refill_date_next_min,
	cast(jsonb_extract_path_text(_airbyte_data, 'days_overdue') as int) as days_overdue,
	cast(jsonb_extract_path_text(_airbyte_data, 'days_lifetime') as int) as days_lifetime,
	cast(jsonb_extract_path_text(_airbyte_data, 'rxs_count') as int) as rxs_count,
	cast(jsonb_extract_path_text(_airbyte_data, 'rx_groups_count') as int) as rx_groups_count,
	cast(jsonb_extract_path_text(_airbyte_data, 'is_autofill') as int) as is_autofill,
	cast(jsonb_extract_path_text(_airbyte_data, 'refills_used_day') as int) as refills_used_day,
	cast(jsonb_extract_path_text(_airbyte_data, 'refills_used_total') as int) as refills_used_total,
	cast(jsonb_extract_path_text(_airbyte_data, 'payment_card_type') as varchar) as payment_card_type,
	cast(jsonb_extract_path_text(_airbyte_data, 'payment_card_last4') as varchar) as payment_card_last4,
	cast(jsonb_extract_path_text(_airbyte_data, 'payment_card_date_expired') as date) as payment_card_date_expired,
	cast(jsonb_extract_path_text(_airbyte_data, 'payment_method_default') as varchar) as payment_method_default,
	cast(jsonb_extract_path_text(_airbyte_data, 'payment_coupon') as varchar) as payment_coupon,
	cast(jsonb_extract_path_text(_airbyte_data, 'tracking_coupon') as varchar) as tracking_coupon,
	cast(jsonb_extract_path_text(_airbyte_data, 'modified_by') as varchar) as modified_by,
	cast(jsonb_extract_path_text(_airbyte_data, 'date_processed') as timestamp) as date_processed
from "datawarehouse".raw._airbyte_raw_analytics_patients_daily_logs