with final as (
    select
        _airbyte_emitted_at,
        _airbyte_ab_id,
        cast(json_value(_airbyte_data, 
    '$."patient_id_cp"') as int) as 'patient_id_cp',
        cast(json_value(_airbyte_data, 
    '$."patient_id_wc"') as int) as 'patient_id_wc',
        cast(json_value(_airbyte_data, 
    '$."first_name"') as varchar(80)) as 'first_name',
        cast(json_value(_airbyte_data, 
    '$."last_name"') as varchar(80)) as 'last_name',
        cast(json_value(_airbyte_data, 
    '$."birth_date"') as date) as 'birth_date',
        cast(json_value(_airbyte_data, 
    '$."patient_note"') as varchar(3072)) as 'patient_note',
        cast(json_value(_airbyte_data, 
    '$."phone1"') as varchar(10)) as 'phone1',
        cast(json_value(_airbyte_data, 
    '$."phone2"') as varchar(10)) as 'phone2',
        cast(json_value(_airbyte_data, 
    '$."email"') as varchar(255)) as 'email',
        cast(json_value(_airbyte_data, 
    '$."patient_autofill"') as int) as 'patient_autofill',
        cast(json_value(_airbyte_data, 
    '$."pharmacy_name"') as varchar(50)) as 'pharmacy_name',
        cast(json_value(_airbyte_data, 
    '$."pharmacy_npi"') as varchar(10)) as 'pharmacy_npi',
        cast(json_value(_airbyte_data, 
    '$."pharmacy_fax"') as varchar(12)) as 'pharmacy_fax',
        cast(json_value(_airbyte_data, 
    '$."pharmacy_phone"') as varchar(12)) as 'pharmacy_phone',
        cast(json_value(_airbyte_data, 
    '$."pharmacy_address"') as varchar(255)) as 'pharmacy_address',
        cast(json_value(_airbyte_data, 
    '$."payment_card_type"') as varchar(20)) as 'payment_card_type',
        cast(json_value(_airbyte_data, 
    '$."payment_card_last4"') as varchar(4)) as 'payment_card_last4',
        cast(json_value(_airbyte_data, 
    '$."payment_card_date_expired"') as date) as 'payment_card_date_expired',
        cast(json_value(_airbyte_data, 
    '$."payment_method_default"') as varchar(50)) as 'payment_method_default',
        cast(json_value(_airbyte_data, 
    '$."payment_coupon"') as varchar(20)) as 'payment_coupon',
        cast(json_value(_airbyte_data, 
    '$."tracking_coupon"') as varchar(20)) as 'tracking_coupon',
        cast(json_value(_airbyte_data, 
    '$."patient_address1"') as varchar(255)) as 'patient_address1',
        cast(json_value(_airbyte_data, 
    '$."patient_address2"') as varchar(255)) as 'patient_address2',
        cast(json_value(_airbyte_data, 
    '$."patient_city"') as varchar(255)) as 'patient_city',
        cast(json_value(_airbyte_data, 
    '$."patient_state"') as varchar(2)) as 'patient_state',
        cast(json_value(_airbyte_data, 
    '$."patient_zip"') as varchar(5)) as 'patient_zip',
        cast(json_value(_airbyte_data, 
    '$."refills_used"') as decimal(5,2)) as 'refills_used',
        cast(json_value(_airbyte_data, 
    '$."patient_status"') as int) as 'patient_status',
        cast(json_value(_airbyte_data, 
    '$."language"') as int) as 'language',
        cast(json_value(_airbyte_data, 
    '$."allergies_none"') as varchar(80)) as 'allergies_none',
        cast(json_value(_airbyte_data, 
    '$."allergies_cephalosporins"') as varchar(80)) as 'allergies_cephalosporins',
        cast(json_value(_airbyte_data, 
    '$."allergies_sulfa"') as varchar(80)) as 'allergies_sulfa',
        cast(json_value(_airbyte_data, 
    '$."allergies_aspirin"') as varchar(80)) as 'allergies_aspirin',
        cast(json_value(_airbyte_data, 
    '$."allergies_penicillin"') as varchar(80)) as 'allergies_penicillin',
        cast(json_value(_airbyte_data, 
    '$."allergies_erythromycin"') as varchar(80)) as 'allergies_erythromycin',
        cast(json_value(_airbyte_data, 
    '$."allergies_codeine"') as varchar(80)) as 'allergies_codeine',
        cast(json_value(_airbyte_data, 
    '$."allergies_nsaids"') as varchar(80)) as 'allergies_nsaids',
        cast(json_value(_airbyte_data, 
    '$."allergies_salicylates"') as varchar(80)) as 'allergies_salicylates',
        cast(json_value(_airbyte_data, 
    '$."allergies_azithromycin"') as varchar(80)) as 'allergies_azithromycin',
        cast(json_value(_airbyte_data, 
    '$."allergies_amoxicillin"') as varchar(80)) as 'allergies_amoxicillin',
        cast(json_value(_airbyte_data, 
    '$."allergies_tetracycline"') as varchar(80)) as 'allergies_tetracycline',
        cast(json_value(_airbyte_data, 
    '$."allergies_other"') as varchar(255)) as 'allergies_other',
        cast(json_value(_airbyte_data, 
    '$."medications_other"') as varchar(3072)) as 'medications_other',
        cast(json_value(_airbyte_data, 
    '$."patient_date_added"') as datetime) as 'patient_date_added',
        cast(json_value(_airbyte_data, 
    '$."patient_date_registered"') as datetime) as 'patient_date_registered',
        cast(json_value(_airbyte_data, 
    '$."patient_date_changed"') as datetime) as 'patient_date_changed',
        cast(json_value(_airbyte_data, 
    '$."patient_date_updated"') as datetime) as 'patient_date_updated'
    from
        analytics_v2._airbyte_raw_goodpill_gp_patients
)
select
    *
from
    final